### ISSUE TITLE
Messages not coming through

### ISSUE THREAD

**Issue by nathanhornby** [leepowellcouk/mongoose-validator#31]
I'm having a hard time getting anything out of the validation process.

I'm using Passport and the `failureFlash: true` argument. The flash object is being populated, but all I'm getting is: `{ error: [ 'Pro validation failed' ] }` (`Pro` being the name of the model/schema) - none of the actual error messages I'm setting using this package.

I don't have this issue when using standard inline validation in the schema.

Am I doing something obviously wrong?

**Comment by leepowellcouk** [comment]
Do you have a simplified code example of the issue?

**Comment by nathanhornby** [comment]
Sure, hopefully this leaves enough detail in place: https://gist.github.com/nathanhornby/60fcf1f37a8c7ad2fd20

**Comment by nathanhornby** [comment]
Ugh, I just noticed that I was declaring one of the validators as `isAscii` when it should be `isLength` - I'm going to go check that wasn't the issue!

**Comment by nathanhornby** [comment]
Darn, unfortunately that wasn't it - I still just get `{ error: [ 'Pro validation failed' ] }` in the flash object.

**Comment by leepowellcouk** [comment]
Could you post the output of the error object for me please from the `save` method.

**Comment by nathanhornby** [comment]
Of course, find the full object here: https://gist.github.com/nathanhornby/a01931b9001792aa0ff6

**Comment by leepowellcouk** [comment]
Ah, ok. So it's using the error.message property. Maybe try this if you want a more detailed output:

    // Passport

    passport.use('local-signup', new LocalStrategy({
      usernameField: 'email',
      passwordField: 'password',
      passReqToCallback: true
    },
    function(req, email, password, done) {
      …
        newPro.save(function(err) {
          if (err) {
            return done(null, false, { message: err.toString() });
          }
          return done(null, newPro);
        });
      …
    })

This is simply making use of mongoose's validation Error object: https://github.com/Automattic/mongoose/blob/master/lib/error/validation.js

Alternatively if you wanted to just display the first error message you could grab the first ValidatorError in the err.errors object.

**Comment by nathanhornby** [comment]
Ah OK - that change gave me the two errors that triggered as a comma separated string (just like it's asking) - how can I simply return the errors object as-is? I just had a couple tries but am struggling to return what I need (sorry still new to node/mongoose!).

**Comment by leepowellcouk** [comment]
Well, the ValidationError object contains a property called `errors` which is a object of path (key) value to ValidatorError objects. I'm not quite sure what you're trying to do.

**Comment by leepowellcouk** [comment]
If you pass an error object to Passport then the flash message will display `error.message`, if you want to pass a custom message for the flash message, then you need to pass an object with a property of `message` (essentially simulating an Error object).

**Comment by nathanhornby** [comment]
Yes that's the object I want to pass back - but I can't as I can only pass back a string (which is oddly limiting, but on Passports end).

I'm looking at walking through the errors and writing each one to `req.flash` myself - as then at least I'll be able to access them individually - just all feels very very clunky!

**Comment by leepowellcouk** [comment]
Where do you want to pass it back to? Into your route handler?

**Comment by nathanhornby** [comment]
Yep (although all I'll be doing there is passing it to the view)

**Comment by leepowellcouk** [comment]
One dirty way would just be to attach it to the req object.

    // Passport

    passport.use('local-signup', new LocalStrategy({
      usernameField: 'email',
      passwordField: 'password',
      passReqToCallback: true
    },
    function(req, email, password, done) {
      …
        newPro.save(function(err) {
          if (err) {
            req.myPassportError = err;
            return done(null, false, { message: err.toString() });
          }
          return done(null, newPro);
        });
      …
    })

Then It should be available to you in the `req` object in your route.

**Comment by nathanhornby** [comment]
Yea I'm currently looking at feeding it directly to the flash object, almost the same techinque:

`// Passport

passport.use('local-signup', new LocalStrategy({
  usernameField: 'email',
  passwordField: 'password',
  passReqToCallback: true
},
function(req, email, password, done) {
  …
    newPro.save(function(err) {
      if (err) {
        if (err.errors) {
          req.flash('errors', err.errors);
        }
        return done(null, false, "Errors found");
      }
      return done(null, newPro);
    });
  …
})`

Although I'm now having issues extracting the values in the view - so I'm not sure that's a valid approach!

My flash object (passed in as `messages`) now looks more like this:

[{ name:
    { properties: [Object],
      message: 'Your company name needs to be between 3 and 64 characters long',

But 

<% if (messages) { %>
  <p><%= messages.name %></p>
<% } %>

Is outputting nothing.

Gah! I'll battle on anyway - you've certainly gone above and beyond getting me in the right direction! Cheers.

**Comment by leepowellcouk** [comment]
Just out of interest - is it really required to pass the full error object across. What is the end result you're looking for? To display all the error messages to the user as a list?

**Comment by nathanhornby** [comment]
I'll be displaying them inline, i.e. along with each respective input field. So having them as a comma separated list isn't ideal.

**Comment by leepowellcouk** [comment]
OK, which version of Express as you using? 3?

**Comment by nathanhornby** [comment]
Latest, so 4.x

**Comment by leepowellcouk** [comment]
Cool. Give me a sec to have a think. If you use connect-flash directly you maybe able to bypass Passport's usage of it, and that might give you a bit more flexibility.

**Comment by nathanhornby** [comment]
Thanks so much Lee - unnecessary but very much appreciated!

**Comment by leepowellcouk** [comment]
Try this ...
https://gist.github.com/leepowellcouk/17d25e5938e014077148

Turn off Passports flash feature, and don't pass the `err` object into it. This uses `req.flash` directly to stash the error messages per path that's got an error. Then in your route handler pass it into the view. So you should be able to access your messages with something like `errors.name` and `errors.uri`.

**Comment by leepowellcouk** [comment]
Ah, just seen that Passport is handling the failure redirect too ...  you might need to change that and use your own callback, or something similar.

**Comment by nathanhornby** [comment]
Awesome thanks Lee - I'll have a play!

**Comment by leepowellcouk** [comment]
No worries - looking again, you should be fine to use the failure redirect as it'll grab the flash messages on the `get` request after the redirect has happened :) 

Let me know how you get on.

**Comment by nathanhornby** [comment]
Woop - works a treat!

**Comment by leepowellcouk** [comment]
Great stuff!
