### ISSUE TITLE
DeprecationWarning: Implicit async custom validators (custom validators that take 2 arguments) are deprecated in mongoose >= 4.9.0

### ISSUE THREAD

**Issue by yuricamara** [leepowellcouk/mongoose-validator#37]
Hi,

I have been receiving this message when a validation process happens with mongoose-validator.

Using:
"mongodb": "2.2.25",
"mongoose": "4.9.4",
"mongoose-validator": "1.2.5", 

The message always says:
See http://mongoosejs.com/docs/validation.html#async-custom-validators for more info

**Comment by leepowellcouk** [comment]
Thanks. I'll investigate - I don't suppose you happen to have a example of this happening I could use do you?

**Comment by yuricamara** [comment]
This happens for any situation with Mongoose  >= 4.9.0. 

When you have time, check my PR, please.

**Comment by leepowellcouk** [comment]
PR merged and published to npm. Thanks for your contribution :)

**Comment by yuricamara** [comment]
You're welcome!
