### ISSUE TITLE
error in new version

### ISSUE THREAD

**Issue by eran10** [leepowellcouk/mongoose-validator#41]
Uncaught Error: Cannot find module "./default-error-messages"
    at webpackMissingModule

are you missing something ?

**Comment by leepowellcouk** [comment]
Shouldn't be - `default-error-messages`is a json file which when loaded by node is parsed. Node attempts to add the .json extension by default. Maybe webpack isn't and that's whats causing the issue. Sorry I'm not a familiar with webpack in fine detail. Could you try modifying the source and adding the .json extension - see if that sorts your issue. If it does then I'm happy to make the change and push out a new patch version.

**Comment by leepowellcouk** [comment]
Just looking at the webpack docs - would the [json-loader ](https://github.com/webpack-contrib/json-loader) work for you here?
