### ISSUE TITLE
validator.js is included as a devDependency

### ISSUE THREAD

**Issue by rockmacaca** [leepowellcouk/mongoose-validator#42]
You should include it as a peerDependency to warn that you're intending to let people choose what version of validator.js to use. Otherwise you should include it as a normal dependency!

**Comment by leepowellcouk** [comment]
Yes, you're correct. Looks like my dependencies got mixed up, and I ended up with mocha as a dependancy instead! Thanks for the heads up. Should be fixed now with 1.3.2
