### ISSUE TITLE
ReDoS in validator

### ISSUE THREAD

**Issue by jasinner** [leepowellcouk/mongoose-validator#46]
Ensure we're using validator 9.4.1 or later to avoid Regular Expression Denial of Service (ReDoS) in validator dependency.

https://snyk.io/vuln/npm:validator:20180218

**Comment by jasinner** [comment]
https://github.com/leepowellcouk/mongoose-validator/pull/47

**Comment by leepowellcouk** [comment]
Merged. Thanks 👍
