### ISSUE TITLE
usigin validator parameters

### ISSUE THREAD

**Issue by davutkara** [leepowellcouk/mongoose-validator#48]
Validator.js, the function is isAlphanumeric(str [, locale]).

I want to send tr_TR for locale parameter, but how can I set here

  validate({
    validator: 'isAlphanumeric',
    passIfEmpty: true,
    message: 'Name should contain alpha-numeric characters only'
  })

**Comment by leepowellcouk** [comment]
Have you tried using the `arguments` property? [https://github.com/leepowellcouk/mongoose-validator#optionarguments---optional](https://github.com/leepowellcouk/mongoose-validator#optionarguments---optional)
